server:
  servlet:
    contextPath: /exercise
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:exercise;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop