CREATE SEQUENCE TOURNAMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE TOURNAMENT(
    TOURNAMENT_ID NUMBER DEFAULT NEXTVAL('TOURNAMENT_SEQ') PRIMARY KEY NOT NULL,
    REWARD_AMOUNT NUMBER NOT NULL,
    CURRENCY      VARCHAR2(3) not null,
    NAME          VARCHAR2(30) not null
);


CREATE SEQUENCE PLAYER_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE PLAYER(
    PLAYER_ID       NUMBER default NEXTVAL('PLAYER_SEQ') primary key not null,
    FIRST_NAME      VARCHAR2(30) not null,
    LAST_NAME       VARCHAR2(30) not null,
    TOURNAMENT_ID   NUMBER,
    STATUS          VARCHAR2(30) not null,
    foreign key (TOURNAMENT_ID) references TOURNAMENT(TOURNAMENT_ID)
);